// Mocks generated by Mockito 5.4.6 from annotations
// in own_auto_care/test/application/use_cases/reminder_use_cases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:own_auto_care/domain/entities/reminder.dart' as _i4;
import 'package:own_auto_care/domain/repositories/reminder_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ReminderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReminderRepository extends _i1.Mock
    implements _i2.ReminderRepository {
  MockReminderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Reminder>> getRemindersByVehicleId(String? vehicleId) =>
      (super.noSuchMethod(
            Invocation.method(#getRemindersByVehicleId, [vehicleId]),
            returnValue: _i3.Future<List<_i4.Reminder>>.value(<_i4.Reminder>[]),
          )
          as _i3.Future<List<_i4.Reminder>>);

  @override
  _i3.Future<_i4.Reminder?> getReminderById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getReminderById, [id]),
            returnValue: _i3.Future<_i4.Reminder?>.value(),
          )
          as _i3.Future<_i4.Reminder?>);

  @override
  _i3.Future<void> saveReminder(_i4.Reminder? reminder) =>
      (super.noSuchMethod(
            Invocation.method(#saveReminder, [reminder]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteReminder(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteReminder, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
